# Generated by Django 4.0.2 on 2022-02-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enderecos',
            new_name='Endereco',
        ),
    ]
